services:
  ten_agent_dev:
    image: ghcr.io/ten-framework/ten_agent_build:0.7.14
    container_name: ten_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT}:${GRAPH_DESIGNER_SERVER_PORT}"
      - "4000:4000"
      - 8000-9001:8000-9001
    volumes:
      - ./:/app
      - ${LOG_PATH}:${LOG_PATH}
      - ../.vscode/:/app/.vscode
      - ../tools/pylint/.pylintrc:/tools/pylint/.pylintrc
      - ../tools/upgrade:/tools/upgrade
    working_dir: /app
    env_file:
      - .env
    networks:
      - ten_agent_network
  # ten_graph_designer:
  #   image: ghcr.io/ten-framework/ten_graph_designer:4cc33b8
  #   container_name: ten_graph_designer
  #   restart: always
  #   ports:
  #     - "3001:3000"
  #   networks:
  #     - ten_agent_network
  #   environment:
  #     - TEN_DEV_SERVER_URL=http://ten_agent_dev:49483
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ten_agent_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    command: [ "--config=/etc/otelcol-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317" # gRPC OTLP
      - "4318:4318" # HTTP OTLP
    depends_on:
      - loki
    networks:
      - ten_agent_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    networks:
      - ten_agent_network

networks:
  ten_agent_network:
    driver: bridge
